services:
  app:
    container_name: flask_app
    build:
      context: .
    command: python main.py
    restart: always
    depends_on:
      - db
      - pgadmin
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
      